# Site settings
title: geocoding.io
email: rupert@2rmobile.com
description: > # this means to ignore newlines until "baseurl:"
  Note that this site is not for "geocoding" or 
  geocoding addresses!  It is a collection 
  of posts, coding snippets, howtos, etc focused 
  on "geo" technologies.  Im just an email away 
  if you want to "geo" chat about something or 
  any of the posts or technologies discussed on 
  this site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://geocoding.io" # the base hostname & protocol for your site
twitter_username: rupertdeguzman
github_username:  rdeguzman

location: "Melbourne, Australia"

# Build settings
markdown: kramdown

# Syntax Highlighter
highlighters: pygments 
